export const IconClassName = 'h-4 w-4';

export const routes = [
  {
    href: `/`,
    label: 'Rezept einlösen',
  },
  {
    href: `/Live Bestand`,
    label: 'Live Bestand',
  },
  {
    href: `/Videosprechstunde`,
    label: 'Videosprechstunde',
  },
  {
    href: `/FAQs`,
    label: 'FAQs',
  },
  {
    href: `/Kontakt`,
    label: 'Kontakt',
  },
];

export const select = [
  {
    id: 1,
    label: 'ADREXpharma',
    checked: false,
  },
  {
    id: 2,
    label: 'Aurora',
    checked: false,
  },
  {
    id: 3,
    label: 'Avaay',
    checked: true,
  },
  {
    id: 4,
    label: 'Bedrocan',
    checked: true,
  },
  {
    id: 5,
    label: 'Cannamedical',
    checked: false,
  },
];

export const product = [
  {
    id: 1,
    title: 'nicht lieferbar',
    Veg: false,
    heading: 'Canify',
    description: 'Cannabis Flos 18/1 PT Mango',
    ingredient1: 'Mango',
    ingredient2: 'Hybrid',
    price: '11,66',
    thc: '18%',
  },
  {
    id: 2,
    title: 'nicht lieferbar',
    Veg: false,
    heading: 'Canify',
    description: 'Cannabis Flos 18/1 PT Mango',
    ingredient1: 'Mango',
    ingredient2: 'Hybrid',
    price: '11,66',
    thc: '18%',
  },
  {
    id: 3,
    title: 'nicht lieferbar',
    Veg: false,
    heading: 'Canify',
    description: 'Cannabis Flos 18/1 PT Mango',
    ingredient1: 'Mango',
    ingredient2: 'Hybrid',
    price: '11,66',
    thc: '18%',
  },
  {
    id: 4,
    title: 'sofort lieferbar',
    Veg: true,
    heading: 'Canify',
    description: 'Cannabis Flos 22/1 PT Ku.Pink Kush DAB Canify',
    ingredient1: 'Pink Kush',
    ingredient2: 'Hybrid',
    price: '11,66',
    thc: '25%',
  },
  {
    id: 5,
    title: 'sofort lieferbar',
    Veg: true,
    heading: 'Canify',
    description: 'Cannabis Flos 22/1 PT Ku.Pink Kush DAB Canify',
    ingredient1: 'Pink Kush',
    ingredient2: 'Hybrid',
    price: '11,66',
    thc: '25%',
  },
  {
    id: 6,
    title: 'sofort lieferbar',
    Veg: true,
    heading: 'Canify',
    description: 'Cannabis Flos 22/1 PT Ku.Pink Kush DAB Canify',
    ingredient1: 'Pink Kush',
    ingredient2: 'Hybrid',
    price: '11,66',
    thc: '25%',
  },
  {
    id: 7,
    title: 'nicht lieferbar',
    Veg: false,
    heading: 'Canify',
    description: 'Cannabis Flos 18/1 PT Mango',
    ingredient1: 'Mango',
    ingredient2: 'Hybrid',
    price: '11,66',
    thc: '18%',
  },
  {
    id: 8,
    title: 'nicht lieferbar',
    Veg: false,
    heading: 'Canify',
    description: 'Cannabis Flos 18/1 PT Mango',
    ingredient1: 'Mango',
    ingredient2: 'Hybrid',
    price: '11,66',
    thc: '18%',
  },
  {
    id: 9,
    title: 'nicht lieferbar',
    Veg: false,
    heading: 'Canify',
    description: 'Cannabis Flos 18/1 PT Mango',
    ingredient1: 'Mango',
    ingredient2: 'Hybrid',
    price: '11,66',
    thc: '18%',
  },
];
